chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #path('', views.index, name='index'),
    path('', views.LoginPage, name='Login'),
    path('SignUp/', views.SignUpPage, name='SignUp'),
    path('ForgotPassword/', views.ForgotPasswordPage, name='ForgotPassword'),
    path('OTP/', views.OTPPage, name='Otp'),
    path('ResetPassword/', views.ResetPasswordPage, name='ResetPassword'),
    path('ProfilePicture/', views.ProfilePicturePage, name='ProfilePicture'),
    path('chat/<str:room_name>/', views.room, name='room'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('chat.urls')),
    path('admin/', admin.site.urls),
]

chat/models.py
from django.db import models

class UserAccount(models.Model):
    Email=models.EmailField(max_length = 254)
    UserID=models.TextField(max_length=30)
    Password=models.TextField(max_length=30)
    FriendList=models.TextField()
    ProfilePicture=models.ImageField()
    objects = models.Manager() 

chat/forms.py
from django import forms
from django.forms import fields
from .models import UserAccount

class UserRegistrationForm(forms.ModelForm):
    Email=forms.EmailField()
    UserID=forms.CharField(max_length=30)
    Password=forms.CharField(widget = forms.PasswordInput())
    RetypePassword=forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model=UserAccount
        fields=['UserID','Email','Password']

class UserLoginForm(forms.Form):
    UserID=forms.CharField(max_length=30)
    Password=forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model=UserAccount
        fields=['UserID','Password']

class ForgotPasswordForm(forms.Form):
    Email = forms.EmailField()
    class Meta:
        model=UserAccount
        fields=['Email']

class OTPForm(forms.Form):
    Otp=forms.CharField(max_length=4)

class ResetPasswordForm(forms.Form):
    newPassword=forms.CharField(widget = forms.PasswordInput())
    reTypeNewPassword=forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model=UserAccount
        fields=['Email','Password']


chat/views.py
from django.shortcuts import render,redirect
from .forms import UserRegistrationForm,UserLoginForm,ForgotPasswordForm,OTPForm,ResetPasswordForm
from django.contrib import messages
from .models import UserAccount
from django.core.mail import EmailMessage
from django.conf import settings
import random

ResetPassword={}

def index(request):
    return render(request, 'chat/index.html')

def LoginPage(Request):
    if Request.method=='GET':
        Login=UserLoginForm(Request.GET)
        UserData=UserAccount.objects.all()
        global UserID
        if Login.is_valid():
            UserID = Login.cleaned_data['UserID']
            Password=Login.cleaned_data['Password']
            userFlag=0
            for user in UserData:
                if UserID==user.UserID and Password==user.Password:
                    userFlag==1
                    return redirect('/chat/lobby/?name=lobby&user='+UserID)
            if userFlag==0:
                messages.error(Request,'Account Doesnt Exist! Try Creating One.')
        else:
            Login=UserLoginForm()
    return render(Request,'Login/Login.html',{'title':'Login'})

def SignUpPage(Request):
    if Request.method == "POST":
        SignUp = UserRegistrationForm(Request.POST)
        UserData=UserAccount.objects.all()
        if SignUp.is_valid():
            UserID = SignUp.cleaned_data['UserID']
            Email=SignUp.cleaned_data['Email']
            Password=SignUp.cleaned_data['Password']
            RetypePassword=SignUp.cleaned_data['RetypePassword']
            userFlag=0
            for user in UserData:
                if UserID == user.UserID:
                    userFlag=1
                    break
            if userFlag==0 and Password==RetypePassword:
                SignUp.save()
                messages.success(Request, f"Hey, {UserID}!")
                return redirect('ProfilePicture')
            elif userFlag==1:
                messages.error(Request,"User Name or Email Already Exists!")
            elif Password!=RetypePassword:
                messages.error(Request, "Passwords Do Not Match!.")
        else:
            SignUp = UserRegistrationForm()
    return render(Request,'Login/SignUp.html',{'title':'SignUp'})


def ForgotPasswordPage(Request):
    if Request.method=='GET':
        ForgotPassword=ForgotPasswordForm(Request.GET)
        UserData=UserAccount.objects.all()
        if ForgotPassword.is_valid():
            Email=ForgotPassword.cleaned_data['Email']
            userFlag=0
            for user in UserData:
                if Email==user.Email:
                    userFlag==1
                    messages.success(Request, f"OTP Sent to Your Mail ID !")
                    O_T_P = str(random.randint(1000,9999))
                    ResetPassword[Email]=O_T_P
                    messageContent=f'Hi,\n      We got a Request to Reset your InstaChat Password.\n    Your OTP is {O_T_P}. If you Ignore this message your Password will not be Changed. '
                    msg = EmailMessage('InstaChat - Password Reset', messageContent,settings.EMAIL_HOST_USER,[Email])
                    msg.send()
                    return redirect('Otp')  
            print(userFlag)
            if userFlag==0:
                messages.error(Request,"Un-Registered Email ID !")  
        else:
            ForgotPassword = ForgotPasswordForm()
    return render(Request,'Login/ForgotPassword.html',{'title':'ForgotPassword'})

def OTPPage(Request):
    if Request.method=='GET':
        FormOTP=OTPForm(Request.GET)
        if FormOTP.is_valid():
            Otp=FormOTP.cleaned_data['Otp']
            if Otp in ResetPassword.values():
                return redirect('ResetPassword')
            else:
                messages.error(Request,"Invalid OTP!")
        else:
            FormOTP=OTPForm()
    return render(Request,'Login/Otp.html',{'title':'Otp'})

def ResetPasswordPage(Request):
    if Request.method=='POST':
        FormResetPassword=ResetPasswordForm(Request.POST)
        UserData=UserAccount.objects.all()
        if FormResetPassword.is_valid():
            newPassword=FormResetPassword.cleaned_data['newPassword']
            reTypeNewPassword=FormResetPassword.cleaned_data['reTypeNewPassword']
            print(newPassword,reTypeNewPassword)
            print(ResetPassword)
            for key,values in ResetPassword.items():
                EmailKey=key
                break
            if newPassword==reTypeNewPassword:
                i=0
                for user in UserData:
                    if EmailKey==user.Email:
                        user.Password=newPassword
                        UserData[i].save()
                        messages.success(Request,'Reset Password Succesful !')
                        return redirect('Login')
                    i+=1
            elif newPassword!=reTypeNewPassword:
                messages.error(Request,'Passwords do not Match !')
        else:
            FormResetPassword=ResetPasswordForm()
    return render(Request,'Login/ResetPassword.html',{'title':'Reset Password'})

def ProfilePicturePage(Request):
    return render(Request,'Login/ProfilePicture.html',{'title':'ProfilePicture'})

def room(request, room_name):
    name=request.GET["name"]
    user=request.GET["user"]
    return render(request, 'chat/room.html', {'room_name': room_name,'name' : name,'user': user})

chat/templates/Login/Base.html
{% load static %}
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" id="bootstrap-css">
        <link href="http://fonts.cdnfonts.com/css/billabong" rel="stylesheet">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'Login/Login.css'%}">
        <link rel="stylesheet" href="{% static 'Login/Chat.css'%}">
        {% if title %}
            <title>InstaChat - {{title}}</title>
        {% endif %}
    </head>
    <body>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

chat/templates/Login/ForgotPassword.html
{% extends 'Login/Base.html' %}
{% block content %}
<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->
  
        <!-- Icon -->
        <div class="fadeIn first">
            <h1 style="font-family: 'Billabong', sans-serif;margin-top:15px;">InstaChat</h1>
        </div>
        {% if messages %}
            <div class="alert alert-info alert-dismissible fade show" align="center">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {% for message in messages %}
                    <div class="alert alert-{{ message.text }}">
                        <h5 style="font-size: 15px;">{{message}}</h5>
                    </div>
                {% endfor%}
            </div>
        {% endif %}
        <!-- Login Form -->
        <form method='GET' action="{% url 'ForgotPassword' %}">
            {% csrf_token %}
            <input type="email" id="id_Email" class="fadeIn second" name="Email" placeholder="E-Mail">
            <a href="{% url 'Otp' %}" style="z-index:10;">
                <input type="submit" class="fadeIn fourth" value="Send OTP">
            </a>
        </form>
  
        <!-- Remind Passowrd -->
        <div id="formFooter">
            <a class="underlineHover" href="/">Back</a>
        </div>
  
    </div>
</div>
{% endblock content %}

chat/templates/Login/Login.html
{% extends 'Login/Base.html' %}
{% block content %}
<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->
  
        <!-- Icon -->
        <div class="fadeIn first">
            <h1 style="font-family:'Billabong', sans-serif;margin-top:15px;">InstaChat</h1>
        </div>
        {% if messages %}
            <div class="alert alert-info alert-dismissible fade show" align="center">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              {% for message in messages %}
                  <div class="alert alert-{{ message.text }}">
                      <h5 style="font-size: 15px;">{{message}}</h5>
                  </div>
              {% endfor%}
            </div>
        {% endif %}
        <!-- Login Form -->
        <form method='GET' action="{% url 'Login' %}">
            {% csrf_token %}
            <input type="text" id="UserID" class="fadeIn second" name="UserID" placeholder="User ID">
            <input type="password" id="Password" class="fadeIn third" name="Password" placeholder="Password">
            <input type="submit" class="fadeIn fourth" value="Log In">
        </form>
  
        <!-- Remind Passowrd -->
        <div id="formFooter">
            <div class="d-flex justify-content-center links">
                <h5 style="font-size: 18px;margin-top:0.25%;">Don't Have an Account ? </h5> <a class="underlineHover" href="/SignUp" style="margin-left:1%;"> Sign Up</a>
            </div>
            <a class="underlineHover" href="/ForgotPassword">Forgot Password?</a>
        </div>
  
    </div>
</div>
{% endblock content %}

chat/templates/Login/Otp.html
{% extends 'Login/Base.html' %}
{% block content %}
<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->
  
        <!-- Icon -->
        <div class="fadeIn first">
            <h1 style="font-family: 'Billabong', sans-serif;margin-top:15px;">InstaChat</h1>
        </div>
        {% if messages %}
            <div class="alert alert-info alert-dismissible fade show" align="center">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {% for message in messages %}
                    <div class="alert alert-{{ message.text }}">
                        <h5 style="font-size: 15px;">{{message}}</h5>
                    </div>
                {% endfor%}
            </div>
        {% endif %}
        <!-- Login Form -->
        <form method='GET' action="{% url 'Otp' %}">
            {% csrf_token %}
            <input type="text" id="Otp" class="fadeIn second" name="Otp" placeholder="Enter OTP">
            <a href="{% url 'ResetPassword' %}"><input  type="submit" class="fadeIn fourth" value="Continue"></a>
        </form>
  
        <!-- Remind Passowrd -->
        <div id="formFooter">
            <a class="underlineHover" href="/ForgotPassword">Back</a>
        </div>
  
    </div>
</div>
{% endblock content %}

chat/templates/Login/ProfilePicture.html
{% extends 'Login/Base.html' %}
{% block content %}
<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->
  
        <!-- Icon -->
        <div class="fadeIn first">
            <h1 style="font-family: 'Billabong', sans-serif;margin-top:15px;">InstaChat</h1>
        </div>
  
        <!-- Login Form -->
        <form>
            <div class="row d-flex justify-content-center">
                <div>
                    <div class="circle image-fluid">
                        <!-- User Profile Image -->
                        <img class="profile-pic image-fluid" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png">
                        <!-- Default Image -->
                        <!-- <i class="fa fa-user fa-5x"></i> -->
                    </div>
                    <div class="p-image">
                        <i class="fa fa-camera upload-button"></i>
                        <input class="file-upload" type="file" accept="image/*"/>
                    </div>
               </div>
            </div>
            <a href="/"><input  type="button" class="fadeIn fourth" value="Continue"></a>
        </form>
        <!-- Remind Passowrd -->
        <div id="formFooter">
            <a class="underlineHover" href="/SignUp">Back</a>
        </div>
    </div>
</div>
{% endblock content %}

chat/templates/Login/ResetPassword.html
{% extends 'Login/Base.html' %}
{% block content %}
<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->
  
        <!-- Icon -->
        <div class="fadeIn first">
            <h1 style="font-family: 'Billabong', sans-serif;margin-top:15px;">InstaChat</h1>
        </div>
        {% if messages %}
            <div class="alert alert-info alert-dismissible fade show" align="center">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {% for message in messages %}
                    <div class="alert alert-{{ message.text }}">
                        <h5 style="font-size: 15px;">{{message}}</h5>
                    </div>
                {% endfor%}
            </div>
        {% endif %}
        <!-- Login Form -->
        <form  method='POST' action="{% url 'ResetPassword' %}">
            {% csrf_token %}
            <input type="password" id="newPassword" class="fadeIn second" name="newPassword" placeholder="New Password">
            <input type="password" id="reTypeNewPassword" class="fadeIn second" name="reTypeNewPassword" placeholder="Re-Type New Password">
            <a href="{% url 'Login' %}">
                <input  type="submit" class="fadeIn fourth" value="Reset">
            </a>
        </form>
  
        <!-- Remind Passowrd -->
        <div id="formFooter">
            <a class="underlineHover" href="/OTP">Back</a>
        </div>
  
    </div>
</div>
{% endblock content %}

chat/templates/Login/Signup.html
{% extends 'Login/Base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="wrapper fadeInDown">
    <div id="formContent">
      <!-- Tabs Titles -->
  
      <!-- Icon -->
      <div class="fadeIn first">
        <h1 style="font-family:'Billabong', sans-serif;margin-top:15px;">InstaChat</h1>
      </div>
      {% if messages %}
        <div class="alert alert-info alert-dismissible fade show" align="center">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {% for message in messages %}
            <div class="alert alert-{{ message.text }}">
              <h5 style="font-size: 15px;">{{message}}</h5>
            </div>
          {% endfor%}
            </div>
      {% endif %}
      <!-- Login Form -->
      <form method="POST" action="{% url 'SignUp' %}">
        {% csrf_token %}
        <input type="email" id="id_Email" class="fadeIn second" name="Email" placeholder="E-Mail">
        <input type="text" id="id_UserID" class="fadeIn second" name="UserID" placeholder="User ID">
        <input type="password" id="id_password1" class="fadeIn third" name="Password" placeholder="Password">
        <input type="password" id="id_password2" class="fadeIn third" name="RetypePassword" placeholder="Re-Type Password">
        <a href="{% url 'ProfilePicture' %}"><input type="submit" class="fadeIn fourth" value="Create Account"></a>
      </form>

      <div id="formFooter">
        <a class="underlineHover" href="/">Back</a>
      </div>
    </div>
</div>
{% endblock content %}

chat/templates/Login/room.html
{% extends 'chat/Base.html' %}
{% block content %}
<div class="container">
    <div class="messaging">
        <div class="inbox_msg">
            <div class="inbox_people">
                <div class="headind_srch">
                    <div class="recent_heading">
                        <h1 style="font-family:'Billabong', sans-serif;color: black;">InstaChat</h1>
                    </div>
                    <div class="srch_bar">
                        <div class="stylish-input-group">
                            <input type="text" class="search-bar"  placeholder="Search" >
                            <span class="input-group-addon">
                                <button type="button"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                            </span> 
                        </div>
                    </div>
                </div>
                <div class="inbox_chat">
                    <div class="chat_list active_chat">
                        <div class="chat_people">
                            <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                            <div class="chat_ib">
                                <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                                <p>Test, which is a new approach to have all solutions astrology under one roof.</p>
                            </div>
                        </div>
                    </div>
                    <div class="chat_list">
                        <div class="chat_people">
                            <div class="chat_img"><img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"></div>
                            <div class="chat_ib">
                                <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                                <p>Test, which is a new approach to have all solutions astrology under one roof.</p>
                            </div>
                        </div>
                    </div>
                    <div class="chat_list">
                        <div class="chat_people">
                            <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                            <div class="chat_ib">
                                <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                                <p>Test, which is a new approach to have all solutions astrology under one roof.</p>
                            </div>
                        </div>
                    </div>
                    <div class="chat_list">
                        <div class="chat_people">
                            <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                            <div class="chat_ib">
                                <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                                <p>Test, which is a new approach to have all solutions astrology under one roof.</p>
                            </div>
                        </div>
                    </div>
                    <div class="chat_list">
                        <div class="chat_people">
                            <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"></div>
                            <div class="chat_ib">
                                <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                                <p>Test, which is a new approach to have all solutions astrology under one roof.</p>
                            </div>
                        </div>
                    </div>
                    <div class="chat_list">
                        <div class="chat_people">
                            <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                            <div class="chat_ib">
                                <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                                <p>Test, which is a new approach to have all solutions astrology under one roof.</p>
                            </div>
                        </div>
                    </div>
                    <div class="chat_list">
                        <div class="chat_people">
                            <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                            <div class="chat_ib">
                                <h5>Sunil Rajput <span class="chat_date">Dec 25</span></h5>
                                <p>Test, which is a new approach to have all solutions astrology under one roof.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="FriendStatus">
                <div class="FriendProfile"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                <div class="FriendName">
                    <h1>Sunil Rajput</h1>
                </div>
            </div>
            <div class="mesgs">
                <div class="msg_history">
                </div>
                <div class="type_msg">
                    <div class="input_msg_write">
                        <input type="text" id="chat-message-input" class="write_msg" placeholder="Type a message" />
                        <button class="msg_send_btn" id="chat-message-submit" type="button">
							<i class="fa fa-paper-plane-o" aria-hidden="true"></i>
						</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);
        const chatSocket = new WebSocket('ws://'+ window.location.host+ '/ws/chat/'+ roomName+ '/');
		flag=false;
        chatSocket.onmessage = function(e) 
		{
			const data = JSON.parse(e.data);
			if(flag==false)
				$(".msg_history").append(data.message);
			flag=false;
        };

        chatSocket.onclose = function(e) 
		{
            console.error('Chat socket closed unexpectedly');
        };

        $('#chat-message-input').focus();
        $('#chat-message-input').keyup(function(e) 
		{
            if (e.keyCode === 13) 
			{
                $('#chat-message-submit').click();
            }
        });
        $('#chat-message-submit').click(function(e) 
		{
			if($('#chat-message-input').val().length>0)
			{
				var d = new Date();
				var months = ["Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"];
				var string='<div class="outgoing_msg"><div class="sent_msg"><p>'+$('#chat-message-input').val()+'</p><span class="time_date">'+d.getHours()+':'+d.getMinutes()+' | '+months[d.getMonth()+1]+' '+d.getDate()+'</span></div></div>';
				$(".msg_history").append(string);
				var string='<div class="incoming_msg"><div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div><div class="received_msg"><div class="received_withd_msg"><p>'+$('#chat-message-input').val()+'</p><span class="time_date">'+d.getHours()+':'+d.getMinutes()+' | '+months[d.getMonth()+1]+' '+d.getDate()+'</span></div></div></div>';
				flag=true;
				chatSocket.send(JSON.stringify(
				{
					'message': string
				}));
				$('#chat-message-input').val('');
			}
        });
    </script>
</div>
{% endblock content %}

chat/templates/chat/Base.html
{% load static %}
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
		<link href="https://fonts.cdnfonts.com/css/billabong" rel="stylesheet">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'Login/Login.css'%}">
        <link rel="stylesheet" href="{% static 'Login/Chat.css'%}">
        {% if title %}
            <title>InstaChat - {{title}}</title>
        {% endif %}
    </head>
    <body>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        </body>
</html>

chat/templates/chat/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>